### ISSUE TITLE
Invalid Header

### ISSUE THREAD

**Issue by CreativeWolf** [a0xnirudh/WebXploiter#15]
Running WebXploiter throws the following error:

`Error while checking user agent.Check module log for details.`

Entries form module.log 

```
2017-04-05 17:37:02,069 - module_log - ERROR - Invalid header value b"Mozilla/5.0 (X11; Ubuntu; Linuxx86_64; rv:39.0) Gecko/20100101 Firefox/39.0'\n"
Traceback (most recent call last):
  File "/home/ubuntu/WebXploiter/Modules/A1_injection/sql.py", line 29, in execute_all_func
    self.check_user_agent(target)
  File "/home/ubuntu/WebXploiter/Modules/A1_injection/sql.py", line 59, in check_user_agent
    flag = str(urllib.request.urlopen(req).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1146, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.5/http/client.py", line 1083, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b"Mozilla/5.0 (X11; Ubuntu; Linuxx86_64; rv:39.0) Gecko/20100101 Firefox/39.0'\n"
```
Any pointers please?

**Comment by dabula-s** [comment]
https://www.reddit.com/r/redditdev/comments/3nvjri/i_could_use_some_help_to_understand_why_im/
