### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by qusaialhaddad** [a0xnirudh/WebXploiter#16]
I am getting error while running the command , all installation went fine. 

this is the error 

Traceback (most recent call last):
  File "./WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by attacker34** [comment]
I am having same problem. Please update the issue .is there anyone??

**Comment by ghost** [comment]
Hi
and i have the same problem

Traceback (most recent call last):
  File "WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by PSNAppz** [comment]
If you need to write code which is Python2 and Python3 compatible you can use the following import
```
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
```

**Comment by ghost** [comment]
Thanks !

2018-01-11 14:21 GMT+04:00 PS Narayanan <notifications@github.com>:
